# Generated by Django 4.2.5 on 2023-10-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
